spring.application.name=teman-belajar

spring.datasource.url=${SPRING_DATASOURCE_URL}

#spring.jpa.show-sql=true

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

supabase.s3.endpoint=${SUPABASE_S3_ENDPOINT}
supabase.s3.access-key=${SUPABASE_ACCESS_KEY}
supabase.s3.secret-key=${SUPABASE_SECRET_KEY}
supabase.s3.region=${SUPABASE_S3_REGION}
supabase.s3.bucket-name=${SUPABASE_BUCKET_NAME}

gemini.api.key=${GOOGLE_API_KEY}
gemini.model.name=${GEMINI_MODEL}
gemini.temperature=0.1
gemini.timeout.seconds=60